### ISSUE TITLE
Error Fetching cars in the inventory

### ISSUE THREAD

**Issue by uniqueshakya** [Adhish-XD/Car-Rental-System#11]
The list of cars is not shown in the inventory

**Comment by ajayshrestha681** [comment]
The error fetching cars in the inventory was solved. the error was solved with correct routing.

**Comment by uniqueshakya** [comment]
![fetchinv](https://github.com/Adhish-XD/VroomCarRental/assets/119477652/cc59d8d1-9e53-4394-9c5c-3329b1728787)
