### ISSUE TITLE
Error adding cars

### ISSUE THREAD

**Issue by uniqueshakya** [Adhish-XD/Car-Rental-System#12]

**Comment by ajayshrestha681** [comment]
Configuration for the the Cloudinary was wrong. So the Image was not being sent to the Cloudinary API, which caused error in adding the cars to the Inventory. The configuration for the Cloudinary was corrected. Now we can add the cars to the inventory without error.
![image](https://github.com/Adhish-XD/VroomCarRental/assets/119273052/8711be12-e8e1-42ea-8db3-d2ebaad76cb2)

**Comment by uniqueshakya** [comment]
![add](https://github.com/Adhish-XD/VroomCarRental/assets/119477652/c5c6757f-c044-46ed-8809-7f4b641e87a4)
