### ISSUE TITLE
Error deleting cars.

### ISSUE THREAD

**Issue by uniqueshakya** [Adhish-XD/Car-Rental-System#13]
The cars are once added in the inventory are not being deleted.

**Comment by ajayshrestha681** [comment]
The cars were not deleting from the inventory because the deleteCarsByid Function was not fetching cars of the selected cars from the inventory. The cars id was fetched with proper routing cars./:Id.

**Comment by uniqueshakya** [comment]
![dlt car](https://github.com/Adhish-XD/VroomCarRental/assets/119477652/92feea0b-7eee-4c2b-90a8-1d607d1620b1)
