### ISSUE TITLE
Unable to send a message to customer service.

### ISSUE THREAD

**Issue by uniqueshakya** [Adhish-XD/Car-Rental-System#16]

**Comment by uniqueshakya** [comment]
<img width="1445" alt="Screenshot 2024-05-17 at 11 11 42 PM" src="https://github.com/Adhish-XD/VroomCarRental/assets/125380011/d83d4199-8483-4fc1-aa93-420aa072a668">

**Comment by fhgjnkf** [comment]
I identified that the variables email, subject, and text were not being properly extracted from the request body. I added the line const { email, subject, text } = req.body; to resolve the error and ensure that the necessary data is retrieved from the request body for email composition and sending.
<img width="1397" alt="Screenshot 2024-05-17 at 11 29 55 PM" src="https://github.com/Adhish-XD/VroomCarRental/assets/125380011/906c4752-5f3f-420b-8c8e-dcafdbb93f2e">
