### ISSUE TITLE
Error encountered while editing the car details.

### ISSUE THREAD

**Issue by uniqueshakya** [Adhish-XD/Car-Rental-System#17]
The details of the car is not being edited.

**Comment by uniqueshakya** [comment]
<img width="1439" alt="Screenshot 2024-05-19 at 10 29 57 AM" src="https://github.com/Adhish-XD/VroomCarRental/assets/125380011/8b54cb04-1ffe-42c5-a62c-ba732500f385">

**Comment by fhgjnkf** [comment]
There was an error in the function of updateCarById.There was a typo which I corrected that ensured that the id variable is accurately retrieved from the request parameters.After making this adjustment the controller function  accurately handled updating a car by its ID.Now,the admin can edit the car info successfully.


<img width="1441" alt="Screenshot 2024-05-19 at 10 32 21 AM" src="https://github.com/Adhish-XD/VroomCarRental/assets/125380011/027e762c-9e9b-4aba-a8a1-574fe1b22487">
<img width="1192" alt="Screenshot 2024-05-19 at 12 22 34 PM" src="https://github.com/Adhish-XD/VroomCarRental/assets/125380011/9a417376-958e-46c9-aff4-30fb983a8c39">
