### ISSUE TITLE
error fetching luxury cars

### ISSUE THREAD

**Issue by uniqueshakya** [Adhish-XD/Car-Rental-System#21]

**Comment by ajayshrestha681** [comment]
Solved the error the function was not fetching luxury car because of the wrong casing of the word category. It was 'Category' instead of 'category'.

**Comment by uniqueshakya** [comment]
![luxury](https://github.com/Adhish-XD/VroomCarRental/assets/119477652/c7e3857d-ea1d-43b6-b91b-42761ae647b6)
