### ISSUE TITLE
error fetching sports cars

### ISSUE THREAD

**Issue by uniqueshakya** [Adhish-XD/Car-Rental-System#22]

**Comment by ajayshrestha681** [comment]
Solved the error the function was not fetching sports car because of wrong casing of the word category. It was 'Category' instead of 'category'.

**Comment by uniqueshakya** [comment]
![sports](https://github.com/Adhish-XD/VroomCarRental/assets/119477652/106c4596-621a-41da-9138-0963988aed69)
