### ISSUE TITLE
Error fetching regular cars

### ISSUE THREAD

**Issue by uniqueshakya** [Adhish-XD/Car-Rental-System#23]

**Comment by uniqueshakya** [comment]
![unnamed](https://github.com/Adhish-XD/VroomCarRental/assets/119477652/e8a0b053-c873-45c4-98c7-7aaf2edc2b07)

**Comment by fhgjnkf** [comment]
The route to fetch all cars (router.get('/', getAllCars);) and the route to fetch regular cars (router.get('/regular', fetchRegularCars);), were missing in the code, which led to an error. I have added both in the car routes file. Now the regular cars are being fetched successfully.
<img width="1455" alt="Screenshot 2024-05-19 at 12 57 02 PM" src="https://github.com/Adhish-XD/VroomCarRental/assets/125380011/22eff22d-a8ae-48cd-92d9-7c0d012c4f4f">
