### ISSUE TITLE
Error fetching regular cars

### ISSUE THREAD

**Issue by Adhish-XD** [Adhish-XD/Car-Rental-System#25]
<img width="1469" alt="Screenshot 2024-05-19 at 12 48 48 PM" src="https://github.com/Adhish-XD/VroomCarRental/assets/119477181/bf381396-2aa0-4e1e-a707-ea1935b5f871">

**Comment by fhgjnkf** [comment]
The route to fetch all cars (router.get('/', getAllCars);) and the route to fetch regular cars (router.get('/regular', fetchRegularCars);), were missing in the code, which led to an error. I have added both in the car routes file. Now the regular cars are being fetched successfully.
<img width="1455" alt="Screenshot 2024-05-19 at 12 57 02 PM" src="https://github.com/Adhish-XD/VroomCarRental/assets/119477181/0a759456-599e-4fa7-bf6a-b2bdc7ca0806">
